version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  multiplayer-server:
    build:
      context: .
      dockerfile: Dockerfile.multiplayer
      target: dev
    network_mode: "host"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://localhost:6379
      - MULTIPLAYER_PORT=3002
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data: